#!/bin/ksh
function exportgp {
    VERSION=0.1

    USAGE=$'[-?\n@(#)$Id: '$0' '${VERSION}'(SYSFS GPIO KSH Library)]'
    USAGE+="[-author?Joshua Taylor <joshua dot taylor at sub dash verses dot org>]"
    USAGE+="[-copyright?2015 Joshua Taylor]"
    USAGE+="[-license?https://www.gnu.org/licenses/gpl-3.0.txt]"
    USAGE+="[+NAME?exportg --- makes a gpio pin available for access]"
    USAGE+="[+DESCRIPTION?$0 exports a gpio pin so that it can be read or written via the SYSFS]"
    USAGE+="[g:gpio]#[gpio?the broadcom GPIO pin number]"
    USAGE+="[d:direction]:[direction:=out?set the GPIO direction.]{
        [in?sets GPIO to input for read.]
        [out?set GPIO to output for write (default)]
    }"
    USAGE+="[p:pull?set pull-up or pull-down. NOTE not all pins have pull-ups/downs.]{
        [up?sets the internal pull-up resister]
        [down?sets the internal pull-down resister]
    }"

	#DEFAULTS

    #DIRECTION=out
	PULLUP=0 PULLDOWN=0
	PIN_NUM=

    while getopts "${USAGE}" O
    do
        case ${O} in
            g)
                PIN_NUM=${OPTARG}
                ;;
            d)
                DIRECTION=${OPTARG}
                case ${DIRECTION} in
                    in)
                        set_direction="set_read"
                        ;;
                    out)
                        set_direction="set_write"
                        ;;
                esac
                ;;
            p)
                if [[ ${OPTARG} =~ (U|u) ]]
                then
                    PULLUP=1
                    PULLDOWN=0
                elif [[ ${OPTARG} =~ (D|d) ]]; then
                    PULLUP=0
                    PULLDOWN=1
                fi
                ;;
            *)
                print -u2 "$0: -g [pin number] -d [direction] [-p u|d]"
                return 1
                ;;
            :)
                print -u2 "$0: ${OPTARG} requires an argument."
                return 1
                ;;

            esac
            shift $OPTIND-1
    done

    sysfs="/sys/class/gpio"
    gpio="${sysfs}/gpio${PIN_NUM}"
    # check for already exported ... 0 is true
    [[ -L ${gpio} ]] && exported=0 || exported=1
    # if it's exported, check if we care about its current setup
    if [[ -n ${DIRECTION} && ${exported}=0 ]]; then
        # check what its at now.
        cur_direction=$(cat ${gpio}/direction)
    else
        # don't care, set default
        DIRECTION=out
    fi

    if [[ ${exported} == 1 && -n ${DIRECTION} ]]; then
        echo "${PIN_NUM}" > ${sysfs}/export
        echo "${DIRECTION}" > ${gpio}/direction
        #${set_direction} ${PIN_NUM}
    elif [[ ${exported} == 0  && (${DIRECTION} != ${cur_direction}) ]]; then
        echo "${DIRECTION}" > ${gpio}/direction
        #${set_direction} ${PIN_NUM}
    elif [[ ${exported} == 1 && -z ${DIRECTION} ]]; then
        echo "${PIN_NUM}" > ${sysfs}/export
        echo "out" > ${gpio}/direction
        #${set_direction} ${PIN_NUM}
    fi

}
