#!/bin/ksh
function setRead {
    VERSION=0.1

    USAGE=$'[-?\n@(#)$Id: '$0' '${VERSION}'(SYSFS GPIO KSH Library)]'
    USAGE+="[-author?Joshua Taylor <joshua dot taylor at sub dash verses dot org>]"
    USAGE+="[-copyright?2015 Joshua Taylor]"
    USAGE+="[-license?https://www.gnu.org/licenses/gpl-3.0.txt]"
    USAGE+="[+NAME?$0 --- GPIO to output]"
    USAGE+="[+DESCRIPTION?$0: sets a GPIO pin to output for writing.]"
    USAGE+="[g:gpio]#[gpio?the broadcom GPIO pin number]"

    while getopts "${USAGE}" O
    do
        case ${O} in
            g) PIN_NUM=${OPTARG}
                ;;
            :) print -u2 "$0: -g pin_number"
                return 1
                ;;
        esac
    done

    [[ -z ${PIN_NUM} ]] && return 1
    gpio=/sys/class/gpio/gpio${PIN_NUM}
    isExported -g ${PIN_NUM} && echo "out" > ${gpio}/direction || return $?
}
